defaults:
  - _self_
  - problem: tsp_aco
  - override hydra/output: local

hydra:
  job:
    chdir: True

# The chosen algorithm
algorithm: reevo # other options are "eoh", "ael"; some problems may not support "ael"

# LLM parameters
model: gpt-3.5-turbo  # LLM model (other options include gpt-4-turbo-preview; GLM-3-Turbo, GLM-4; llama3-70b and others supported by llama api, see https://docs.llama-api.com/quickstart)
temperature: 1  # temperature for chat completion

# Main GA loop parameters
max_fe: 100 # maximum number of function evaluations
pop_size: 10 # population size for GA
init_pop_size: 30 # initial population size for GA
mutation_rate: 0.5 # mutation rate for GA
timeout: 20 # timeout for evaluation of a single heuristic
diversify_init_pop: True # whether to diversify the initial population